# Generated by Django 5.0.7 on 2024-07-11 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Subject', models.CharField(max_length=70)),
                ('Message', models.TextField()),
                ('Phone', models.BigIntegerField()),
                ('Created_At', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(choices=[('IN', 'India'), ('US', 'United States'), ('CN', 'China'), ('JP', 'Japan'), ('DE', 'Germany'), ('GB', 'United Kingdom'), ('FR', 'France'), ('IT', 'Italy'), ('BR', 'Brazil'), ('CA', 'Canada'), ('AU', 'Australia'), ('RU', 'Russia'), ('MX', 'Mexico'), ('ES', 'Spain'), ('KR', 'South Korea'), ('SA', 'Saudi Arabia'), ('ZA', 'South Africa'), ('ID', 'Indonesia'), ('NG', 'Nigeria'), ('EG', 'Egypt'), ('AR', 'Argentina'), ('PK', 'Pakistan'), ('BD', 'Bangladesh'), ('TR', 'Turkey'), ('IR', 'Iran'), ('VN', 'Vietnam'), ('PH', 'Philippines'), ('TH', 'Thailand'), ('MY', 'Malaysia'), ('NL', 'Netherlands'), ('CH', 'Switzerland'), ('SE', 'Sweden'), ('BE', 'Belgium'), ('AT', 'Austria'), ('PL', 'Poland'), ('NO', 'Norway'), ('UA', 'Ukraine'), ('GR', 'Greece'), ('CZ', 'Czech Republic'), ('RO', 'Romania'), ('HU', 'Hungary'), ('PT', 'Portugal'), ('IE', 'Ireland'), ('FI', 'Finland'), ('DK', 'Denmark'), ('NZ', 'New Zealand'), ('CL', 'Chile'), ('CO', 'Colombia'), ('SG', 'Singapore'), ('HK', 'Hong Kong'), ('AE', 'United Arab Emirates')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(choices=[('flowering', 'Flowering Plants'), ('succulent', 'Succulents'), ('vegetable', 'Vegetables'), ('herb', 'Herbs'), ('fruit', 'Fruit Trees'), ('ornamental', 'Ornamental Plants'), ('cacti', 'Cacti'), ('indoor', 'Indoor Plants'), ('aquatic', 'Aquatic Plants')], max_length=60)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Description', models.TextField(max_length=70)),
                ('Stock', models.CharField(choices=[(0, 'Out of Stock'), (1, 'Low Stock'), (2, 'Medium Stock'), (3, 'High Stock')], max_length=60)),
                ('Image', models.ImageField(upload_to='Photos')),
            ],
        ),
        migrations.CreateModel(
            name='PlantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CAT_Name', models.CharField(choices=[('flowering', 'Flowering Plants'), ('succulent', 'Succulents'), ('vegetable', 'Vegetables'), ('herb', 'Herbs'), ('fruit', 'Fruit Trees'), ('ornamental', 'Ornamental Plants'), ('cacti', 'Cacti'), ('indoor', 'Indoor Plants'), ('aquatic', 'Aquatic Plants')], max_length=60)),
                ('Description', models.TextField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=50)),
                ('Date_Joined', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(choices=[('IN', [('KA', 'Karnataka'), ('MH', 'Maharashtra'), ('DL', 'Delhi'), ('GJ', 'Gujarat')]), ('US', [('CA', 'California'), ('TX', 'Texas')]), ('CN', [('BJ', 'Beijing'), ('SH', 'Shanghai'), ('GD', 'Guangdong')]), ('JP', [('TK', 'Tokyo'), ('OS', 'Osaka')]), ('DE', [('BE', 'Berlin'), ('BW', 'Baden-Württemberg'), ('BY', 'Bavaria')]), ('GB', [('ENG', 'England'), ('SCT', 'Scotland')]), ('FR', [('IDF', 'Île-de-France'), ('PACA', "Provence-Alpes-Côte d'Azur"), ('ARA', 'Auvergne-Rhône-Alpes')]), ('IT', [('LZ', 'Lazio'), ('LOM', 'Lombardy')]), ('BR', [('SP', 'São Paulo'), ('RJ', 'Rio de Janeiro'), ('MG', 'Minas Gerais')]), ('CA', [('ON', 'Ontario'), ('QC', 'Quebec')]), ('AU', [('NSW', 'New South Wales'), ('VIC', 'Victoria'), ('QLD', 'Queensland')]), ('RU', [('MOW', 'Moscow'), ('SPE', 'Saint Petersburg')]), ('MX', [('CMX', 'Mexico City'), ('NLE', 'Nuevo León'), ('JAL', 'Jalisco')]), ('ES', [('MD', 'Madrid'), ('CT', 'Catalonia')]), ('KR', [('11', 'Seoul'), ('26', 'Busan'), ('27', 'Daegu')]), ('SA', [('01', 'Riyadh'), ('02', 'Maka')]), ('ZA', [('GP', 'Gauteng'), ('WC', 'Western Cape'), ('KZN', 'KwaZulu-Natal')]), ('ID', [('JK', 'Jakarta'), ('JB', 'West Java')]), ('NG', [('LA', 'Lagos'), ('FC', 'Federal Capital Territory'), ('KN', 'Kano')]), ('EG', [('C', 'Cairo'), ('GZ', 'Giza')]), ('AR', [('B', 'Buenos Aires'), ('C', 'Córdoba'), ('S', 'Santa Fe')]), ('PK', [('PB', 'Punjab'), ('SD', 'Sindh')]), ('BD', [('DHK', 'Dhaka'), ('CTG', 'Chittagong'), ('RAJ', 'Rajshahi')]), ('TR', [('34', 'Istanbul'), ('06', 'Ankara')]), ('IR', [('THR', 'Tehran'), ('ISF', 'Isfahan'), ('KHZ', 'Khuzestan')]), ('VN', [('HN', 'Hanoi'), ('HCM', 'Ho Chi Minh City')]), ('PH', [('00', 'Metro Manila'), ('01', 'Ilocos Region'), ('02', 'Cagayan Valley')]), ('TH', [('10', 'Bangkok'), ('40', 'Khon Kaen')]), ('MY', [('10', 'Kuala Lumpur'), ('11', 'Putrajaya'), ('01', 'Johor')]), ('NL', [('NH', 'North Holland'), ('ZH', 'South Holland')]), ('CH', [('ZH', 'Zurich'), ('GE', 'Geneva'), ('VD', 'Vaud')]), ('SE', [('ST', 'Stockholm'), ('VG', 'Västra Götaland')]), ('BE', [('VAN', 'Antwerp'), ('OVL', 'East Flanders'), ('WVL', 'West Flanders')]), ('AT', [('WI', 'Vienna'), ('NOE', 'Lower Austria')]), ('PL', [('MZ', 'Masovian'), ('ML', 'Lesser Poland'), ('DS', 'Lower Silesia')]), ('NO', [('03', 'Oslo'), ('11', 'Rogaland')]), ('UA', [('30', 'Kyiv'), ('32', 'Kyiv Oblast'), ('48', 'Odessa')]), ('GR', [('I', 'Attica'), ('C', 'Central Macedonia')]), ('CZ', [('PR', 'Prague'), ('ST', 'Central Bohemia'), ('JM', 'South Moravia')]), ('RO', [('B', 'Bucharest'), ('CJ', 'Cluj')]), ('HU', [('BU', 'Budapest'), ('PE', 'Pest'), ('BA', 'Baranya')]), ('PT', [('LIS', 'Lisbon'), ('POR', 'Porto')]), ('IE', [('D', 'Dublin'), ('CW', 'Carlow'), ('WW', 'Wicklow')]), ('FI', [('18', 'Southwest Finland'), ('19', 'Pirkanmaa')]), ('DK', [('84', 'Capital Region of Denmark'), ('82', 'Central Denmark Region'), ('81', 'North Denmark Region')]), ('NZ', [('AUK', 'Auckland'), ('WGN', 'Wellington')]), ('CL', [('RM', 'Santiago Metropolitan'), ('VS', 'Valparaíso')]), ('CO', [('DC', 'Bogotá'), ('ANT', 'Antioquia'), ('VAS', 'Valle del Cauca')]), ('SG', [('01', 'Central Region'), ('02', 'North Region')]), ('HK', [('HKI', 'Hong Kong Island'), ('KLN', 'Kowloon')]), ('AE', [('AZ', 'Abu Dhabi'), ('DU', 'Dubai')])], max_length=50)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.country')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(choices=[('KA', 'Bangalore'), ('MH', 'Mumbai'), ('DL', 'New Delhi'), ('CA', 'Los Angeles'), ('TX', 'Houston'), ('BJ', 'Beijing'), ('SH', 'Shanghai'), ('GD', 'Guangzhou'), ('TK', 'Tokyo'), ('OS', 'Osaka'), ('BE', 'Berlin'), ('BW', 'Stuttgart'), ('BY', 'Munich'), ('ENG', 'London'), ('SCT', 'Edinburgh'), ('IDF', 'Paris'), ('PACA', 'Marseille'), ('ARA', 'Lyon'), ('LZ', 'Rome'), ('LOM', 'Milan'), ('SP', 'São Paulo')], max_length=50)),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.state')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Quantity', models.CharField(choices=[('low', 'Low Quantity'), ('medium', 'Medium Quantity'), ('high', 'High Quantity')], max_length=60)),
                ('Order_ID', models.UUIDField()),
                ('Order_Status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=60)),
                ('Plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.plant')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.user'),
        ),
        migrations.CreateModel(
            name='PaymentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking', models.CharField(choices=[('website', 'Website'), ('mobile_app', 'Mobile App'), ('phone', 'Phone'), ('email', 'Email'), ('in_person', 'In Person'), ('social_media', 'Social Media'), ('agent', 'Agent')], max_length=60)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Payment_Mode', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('paypal', 'PayPal'), ('other', 'Other')], max_length=60)),
                ('Payment_Status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=60)),
                ('Payment_Date', models.DateField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='OrderTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.CharField(choices=[('low', 'Low Quantity'), ('medium', 'Medium Quantity'), ('high', 'High Quantity')], max_length=60)),
                ('Total_Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Order_Date', models.DateField()),
                ('Delivery_Date', models.DateField()),
                ('Status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=60)),
                ('Plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.plant')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.IntegerField(blank=True, null=True)),
                ('Comment', models.TextField()),
                ('Review_Date', models.DateField()),
                ('Plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.plant')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BOD', models.DateField()),
                ('Address', models.TextField(max_length=70)),
                ('Phone_No', models.BigIntegerField()),
                ('Image', models.ImageField(upload_to='Photos')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.user')),
            ],
        ),
    ]
