# Generated by Django 5.0.7 on 2024-07-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Date_Joined',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Date_of_birth',
            field=models.DateField(),
        ),
    ]
