# Generated by Django 5.1.6 on 2025-03-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_alter_user_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Date_of_birth',
        ),
        migrations.AlterField(
            model_name='plant',
            name='Stock',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='productcart',
            name='Order_ID',
            field=models.CharField(max_length=50),
        ),
    ]
